apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    role: kibana
spec:
  replicas: 1
  selector:
    role: kibana
  template:
    metadata:
      labels:
        role: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:5.2.0
        env:
        - name: KIBANA_ES_URL
          value: "http://172.19.2.51:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
